# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                     RABBITMQ                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: rabbitmq-cloud-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-cloud-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 

---
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                ACCOUNT-SERVICE DATABASE             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-service-db-pvc
spec:
  storageClassName: account-service-db-cloud-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: account-service-db-cloud-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

---
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                ALERT-SERVICE DATABASE             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-service-db-pvc
spec:
  storageClassName: alert-service-db-cloud-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alert-service-db-cloud-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2