apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
stringData:
    # rabbitmq
    RABBITMQ_HOSTNAME: "cso-rabbitmq"
    RABBITMQ_DEFAULT_USER: "csoadmin"
    RABBITMQ_DEFAULT_PASS: "@CSO2023"
    RABBITMQ_USER: "csoadmin"
    RABBITMQ_PASS: "@CSO2023"
    RABBITMQ_ACCOUNT_QUEUE: "account_queue"
    RABBITMQ_ALERT_QUEUE: "alert_queue"
    # account-service-db
    ACCOUNT_SERVICE_POSTGRES_USER: "postgres"
    ACCOUNT_SERVICE_POSTGRES_PASSWORD: "postgres"
    ACCOUNT_SERVICE_POSTGRES_DB: "cso-account-service-prod-db"
    ACCOUNT_SERVICE_POSTGRES_PORT: "5432"
    ACCOUNT_SERVICE_POSTGRES_HOST: "cso-account-service-db"
    # alert-service-db
    ALERT_SERVICE_POSTGRES_USER: "postgres"
    ALERT_SERVICE_POSTGRES_PASSWORD: "postgres"
    ALERT_SERVICE_POSTGRES_DB: "cso-alert-service-prod-db"
    ALERT_SERVICE_POSTGRES_PORT: "5432"
    ALERT_SERVICE_POSTGRES_HOST: "cso-alert-service-db"
    # gateway
    GATEWAY_PORT: "8080"
    # account-microservice
    ACCOUNT_MICROSERVICE_SERVICE_PORT: "8081"
    ACCOUNT_MICROSERVICE_LOCAL_WEBSITE_URL: "http://localhost:4200"
    ACCOUNT_MICROSERVICE_DEPLOYED_WEBSITE_URL: "http://85.215.42.80"
    ACCOUNT_MICROSERVICE_GMAIL_APP_PASSWORD: "rcphektqshqvsxmb"
    ACCOUNT_MICROSERVICE_GMAIL_USER: "besitter.main"
    ACCOUNT_MICROSERVICE_EMAIL: "besitter.main@gmail.com"
    ACCOUNT_MICROSERVICE_EMAIL_VERIFICATION_SECRET_KEY: "5c0c3f5d-3b37-4b3b-b278-e366dca90f53"
    ACCOUNT_MICROSERVICE_PASSWORD_RESET_EMAIL_SECRET_KEY: "4049a4a1-b566-48f7-800e-ec8984695666"
    ACCOUNT_MICROSERVICE_CLOUDINARY_CLOUD_NAME: "dtpbdl3oy"
    ACCOUNT_MICROSERVICE_CLOUDINARY_API_KEY: "985576946121343"
    ACCOUNT_MICROSERVICE_CLOUDINARY_API_SECRET: "Mp6MIU4TijU1gFVh5lv4bY-TWTU"
    # alert-microservice
    ALERT_MICROSERVICE_SERVICE_PORT: "8082"
    ALERT_MICROSERVICE_LOCAL_WEBSITE_URL: "http://localhost:4200"
    ALERT_MICROSERVICE_DEPLOYED_WEBSITE_URL: "http://85.215.42.80"
    ALERT_MICROSERVICE_ELASTICSEARCH_NODE: "https://85.215.42.80:9200"
    ALERT_MICROSERVICE_ELASTICSEARCH_USERNAME: "elastic"
    ALERT_MICROSERVICE_ELASTICSEARCH_PASSWORD: "ffqHI+TN93MkVpfKqeBR"
    ALERT_MICROSERVICE_PETALERT_SCRAPER_SERVICE_URL: "http://cso-pet-alert-scraper:3000/start-scraping"
    # pet-alert-scraper
    PET_ALERT_SCRAPPER_GATEWAY_URL: "http://cso-gateway:8080/api/v0.0.1/alert-svc/import-alerts"
    # common
    APP_VERSION: "0.0.1"
    ACCESS_TOKEN_SECRET_KEY: "ef796922-14ba-43a3-9bc7-c5b7a71a6be1"
    REFRESH_TOKEN_SECRET_KEY: "0366be2d-2a44-421f-a933-518db1df46eb"
    SWAGGER_USER: "csoadmin"
    SWAGGER_PASSWORD: "@CSO2023"
    ENVIRONMENT: "PROD"
