name: cd

on:
  push:
    branches: ["staging"]
jobs:
  deploy:
    name: Deploy latest changes
    runs-on: ubuntu-latest
    steps:
      - name: Pulling latest updates
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd backend
            git switch staging
            git pull origin staging
      - name: Deploying changes
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd backend/k8s/staging
            kubectl delete -f .
            kubectl apply -f .
            kubectl get all
